top_merchants_list = \
["amc market fair"
,"ave m"
,"deli grill"
,"food mart sour"
,"greentree rd"
,"leaf clover protein"
,"market c"
,"marketside"
,"meeting house"
,"pbi flagler gou west palm"
,"retr retro f staten"
,"victory blvd"
,"w indiantown rd"
,"west cheesman"
,".cvs store v"
,"a to z unlimited wirel"
,"aa"
,"academy sports + outdo"
,"adobe ps cloud trial"
,"aeusd"
,"albertsons las"
,"albertsons lemon"
,"am pm portla"
,"ami general store llc anna"
,"amocofa"
,"antilles cuisine llc"
,"apple"
,"arbys"
,"arcoyunni"
,"associate westche"
,"atrium cafe"
,"audible"
,"autozone ricky la"
,"az vape llc"
,"barnes"
,"barnesnob"
,"bcf sports"
,"beachside snack folly"
,"bealls ou lady"
,"belly busters seafood ocean"
,"belsan bait and tackle"
,"belton parks and recre"
,"big lots main st"
,"big lots pleasan"
,"bitent"
,"blessed to market"
,"blizzard entertainment"
,"blush mark outfitters los"
,"bombay house inc"
,"bookoff"
,"boones market qps los"
,"bp"
,"bpbento"
,"bpes"
,"bpgolf"
,"bpmahil"
,"bpmorga"
,"bppats"
,"bpquali winston"
,"bpshiv"
,"bpyogis"
,"briggs nursery n."
,"broad street mar"
,"brooklyn schermer"
,"bubbleology clinton"
,"buds cou s broad"
,"buffalos golden corne"
,"burr petroleum c"
,"campus bo manley colle"
,"carls jr"
,"caseys"
,"casino beach pier ride seaside"
,"cefco"
,"chenery market san"
,"chickfila"
,"chipotle"
,"chisholm crn"
,"chubby liquo"
,"chuck e cheese"
,"cinergy amarillovista"
,"circle k"
,"citgo go go gas"
,"ckebotskys lake char lake"
,"claires center center"
,"claires"
,"clanton rd. citg"
,"clark"
,"climbzone"
,"cmsbettoli trading co"
,"cmsvendatlantic domin virginia"
,"cmsvendcv richmond n"
,"cmsvendcv san antonio"
,"cntback.co"
,"coastal water park sol saint"
,"coca cola lawrencevill"
,"conserv fuel san luis"
,"conserv fuel santa"
,"country cupboar"
,"country fair"
,"cracker b us hwy southern"
,"crunchyroll anime"
,"crunchyroll membershi"
,"culvers of lockport"
,"cvspharm"
,"d&w quick cascade grand"
,"dairy queen"
,"dari mart main st"
,"dba nino conveni"
,"dds discount"
,"defy fort dynasty fort"
,"del sol panama city be panama city"
,"destin"
,"disney store"
,"docs country mart"
,"dollar ge dg"
,"dollar tr"
,"dollarge"
,"dollartre "
,"dott"
,"dsw"
,"dunkin"
,"e tremont family deli"
,"e troy mobil east"
,"eatstreet"
,"ebay us"
,"ebayincship"
,"ebony trading"
,"enmarket"
,"epcfortnite"
,"etsy"
,"everi"
,"excel bike and fitness"
,"exeter"
,"exit sunrise islip"
,"express m highway water"
,"exxon weston service c"
,"ez mart"
,"fairway food ma north"
,"family dollar"
,"family fa n lake s boyne"
,"favor"
,"fe lowell south"
,"five guys"
,"food city"
,"food giant little"
,"food lion"
,"foxy drive in"
,"fredmeye fred meyer"
,"frysfood"
,"fufu deli and grocery saint"
,"funimation productions"
,"gamestop"
,"ganesh"
,"garden city mini mart murrells"
,"gd juniper"
,"ggaming"
,"glacier way"
,"glam"
,"glossier"
,"gnc"
,"goodwill"
,"google"
,"gordon gate shopt fort"
,"gracy food mart"
,"great american cookie"
,"gringos taco shack toms"
,"grubhubmcdonalds new"
,"grubhubwendys new"
,"h & h liquor"
,"hamilton park e"
,"hangar n nova r daytona"
,"happy lemon"
,"hard rock"
,"harps fuel west"
,"harris te hillsbo"
,"hartway motors inc"
,"harveys w oak st mc"
,"heb gas"
,"hidden ridge rv"
,"highland main st"
,"highway quic"
,"hills fam e th st"
,"hilton"
,"hobbylobb"
,"hollister"
,"hop n shop food store"
,"hot diggity dawg"
,"hottopic"
,"hudson"
,"hypeflags"
,"hyvee i cty mkt grl iowa"
,"ingles markets"
,"intl epss acq euro"
,"island republic st simons"
,"jacksons iga"
,"jays mart"
,"jesses pizza"
,"jet food stores east"
,"jimmy johns"
,"joes shopwell"
,"jordans kwik st"
,"js hallmark"
,"junction lanes family"
,"jwg beauty supply east st."
,"kalahari retail wi wisconsin"
,"kalaharibiggameroom s"
,"key foods grand st"
,"king soop"
,"kings mart conoc"
,"kirklands"
,"kitrevival"
,"kohls "
,"kolache factory"
,"kroger"
,"lafesta brick & brew p"
,"lncln prk zoo"
,"lowes"
,"lululemoncom"
,"lyft"
,"lyons dairy bar"
,"m&t ocean ga w ocean"
,"madrag"
,"main street k los"
,"mapco"
,"marathon petro"
,"marcus arnold cine eco"
,"market street"
,"market@work"
,"marshalls"
,"mastercard st."
,"maverik"
,"maverik st."
,"mcdonalds"
,"microsoft"
,"minit mart eg kansas"
,"miracle car wash fl boca"
,"mountain mart"
,"mtanyct paygo new"
,"murphy express"
,"murphyatwal"
,"myvendingrewards camel"
,"natures food patch"
,"nd and charles"
,"netflix"
,"netflix los"
,"nhs inc."
,"nintendo americaus"
,"njt ny penn sta new"
,"oak speedcheck"
,"oakland marathon"
,"ocean lake store myrtle"
,"oculus menlo"
,"office de texas av college"
,"office ma s hollyw"
,"on run coffee shop"
,"one stop"
,"one stop shop"
,"orange county c c conc"
,"orangeland rv park"
,"pai iso"
,"panda express"
,"pandora of millenia ma"
,"panera bread state"
,"paypal"
,"pbc stone mountain stone"
,"peoples grocery"
,"petsmart  fountain"
,"pizza land inc"
,"pizzeria limone cottonwood"
,"playstation"
,"pleasantburg"
,"popeye"
,"potbelly"
,"ppapplebill"
,"price chopper"
,"prime video"
,"publix"
,"pump and pantry"
,"purplepriso"
,"quality car wash"
,"queen villag"
,"queens market"
,"quick chek food pompton"
,"quick way"
,"qv lincoln"
,"ralphs  irvine newport"
,"ralphs  sepulve manhattan"
,"ramsey s n walnut"
,"rave"
,"redbox dvd rental oakbrook"
,"reg valley mall"
,"riot lnyqkpunb"
,"riot lnzbzspct"
,"ritas italian ice"
,"rite aid"
,"rodney praham s little"
,"rooster tea costa"
,"ross store grand"
,"ross stores"
,"royal oil san"
,"rue route"
,"s & d deli pk"
,"safeway mill"
,"sally bea steger t"
,"sams club sams club"
,"samsclub"
,"shein"
,"shell"
,"shelter island pharmac shelter"
,"smiths fo e. suns"
,"smiths fo south sta"
,"snak shak wywd"
,"sp fashionnova"
,"sp miss a stores"
,"sp sa company"
,"sparkles of smyrna"
,"spencer`s ice cream st"
,"splice"
,"spotify usa new"
,"sq basands vending se fort"
,"sq konaice of bel ai"
,"sq moab coffee roaste"
,"sq mountain view coff"
,"sq sewickley confecti"
,"sq sidelines"
,"sq studio elite"
,"sq sweet petes candy"
,"sq t&f styles little"
,"sq vdogschicago"
,"starbucks"
,"steam games"
,"steam purchase"
,"steamgames"
,"stop & save"
,"stop & shop"
,"stop & shop"
,"stop n go"
,"stripes san"
,"subway"
,"subway oa washingt"
,"sugar kingdom oc st ocean"
,"sunoco"
,"sunstop lake"
,"super foods"
,"super dollar"
,"superior market"
,"t j maxx nw arte"
,"taco bell"
,"target"
,"tbkfc ocean"
,"the alley rainbow"
,"the big squeezy baton"
,"the funplex mt laurel mount"
,"the market at w wintergreen"
,"the timberland company"
,"tianlimedic"
,"tienda la highway fort"
,"time wise"
,"time wise  the"
,"tjmaxx bowling"
,"tjmaxx rte. east"
,"tropical smoothie"
,"tropical smoothie"
,"tst dawsons yogurt santa rosa"
,"txubill payment"
,"uber"
,"ulta"
,"union bank & trust co"
,"unique be dr mart fort"
,"uptown beauty"
,"urban air adventure pa"
,"urban air lake grove lake"
,"us foods"
,"usa soda snausaarcad"
,"usa soda snausaavi f"
,"usa soda snausac & l"
,"usa soda snausasnack"
,"usaavi foodsystems"
,"usasnack soda vendi"
,"valle`s produce"
,"venmo new"
,"venmobosworth rayna new york"
,"venmomccaffrey emma new york"
,"venmoshepherd parke new york"
,"vicky bakery v"
,"vioc"
,"wagoners your"
,"walgreens"
,"weis markets"
,"wendys indn hbr"
,"wesco"
,"whataburger"
,"winners circle"
,"xsolla lunarclient"
,"xsolla roblox"
,"yourscoreandmore"
,"zaxbys san"
,"amazon"
,"7-eleven"
,"walmart"
,"doordash"
,"five belo"]